name: GitHub Actions DotNet
on: 
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 7.0.x
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: true
      BUILD_CONFIGURATION: Release
      PROJECT_PATH: 'WebApplicationIntcomex'
      PROJECT_TEST_PATH: 'UnitTest'
      AZURE_WEBAPP_NAME: 'WebAppGroup7'
      AZURE_WEBAPP_PACKAGE_PATH: '.' 
    steps:
      - name: Check out repository code ('${{ github.repository }}' cloned to the runner)
        uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK (${{ env.DOTNET_CORE_VERSION }})
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
 
      - name: Restore Packages
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build - .NET Core ${{ env.DOTNET_CORE_VERSION }}
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: "${{ env.PROJECT_PATH }}"
        
      - name: Unit Tests 
        run: dotnet test ${{ env.PROJECT_TEST_PATH }}

      - name: Publish artifact
        run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/.net-app'
        working-directory: "${{ env.PROJECT_PATH }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.PROJECT_PATH}}
  
  deploy:
    runs-on: windows-latest
    needs: build-test
    environment:
      name: 'development'
      url: 'webappgroup7.azurewebsites.net'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WebApplicationIntcomex'
